name: bas-app

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345678
      MONGO_INITDB_ROOT_DATABASE: bas-app
    command:
      - '--logpath'
      - '/var/log/mongodb/mongod.log'
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongodb_data:/data/db
      - ./docker/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    
  nestjs:
    image: node:22-alpine
    container_name: nestjs_container
    working_dir: /app
    command: 'npm run start:dev'
    ports:
      - 3000:3000
    volumes:
      - ./api:/app

  angular:
    image: node:22-alpine
    container_name: angular_container
    working_dir: /app
    command: 'npm run start:docker'
    ports:
      - 4200:4200
    volumes:
      - ./web:/app
